### ISSUE TITLE
Modify the entry point to accept only the last 5 digits of the NIN number instead of the entire NIN number.

### ISSUE THREAD

**Issue by stathas** [bol-project/bol-wallet#188]
The application uses only the last 5 digits of the NIN, which it mixes with the name and date of birth to generate the short hash for the codename. 
Since many people are hesitant to provide their NIN to the application, I suggest that the application only request the last 5 digits of the NIN number.
Therefore, in the certification matrix file, where the full NIN number is currently listed, only the last 5 digits of the NIN number will now be displayed. 
We will also change the nin.json file, and the regular expressions will be adjusted to only accommodate the last 5 digits. Additionally, there is no problem for those who have already created accounts with the previous version, where the edi is calculated with the full NIN, which the certifier sees within the matrix files, while with the new version, it will be calculated with the last 5 digits.

**Comment by theofanis** [comment]
@stathas, let's close this if it's covered with #191 and #192. Thank you!
